# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  theme = {
    pname = "theme";
    version = "b6611843a89c3766a1b3e936eaa5b3e068814eaa";
    src = fetchFromGitHub ({
      owner = "gethugothemes";
      repo = "bookworm-light";
      rev = "b6611843a89c3766a1b3e936eaa5b3e068814eaa";
      fetchSubmodules = false;
      sha256 = "sha256-O/J0/3ltMw9hbTHTyLZhR8N3oLViNPex5PlJ+HP+3zg=";
    });
    date = "2022-10-22";
  };
}
