name: Deploy to GH pages

on:
  push:
    branches:
      - bookworm

jobs:
  deploy:
    name: Deploy job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Nix Flakes doesn't work on shallow clones
      - name: Install nix with flakes
        uses: cachix/install-nix-action@v16
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.6.0pre20211228_ed3bc63/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Build static site
        run: nix build .#home.x86_64-linux
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/bookworm'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
